# 加载所需的包
library(ggraph)
library(igraph)
library(tidyverse)
library(viridis)

# 创建分类数据（包含Total节点）
vertices <- data.frame(
  name = c('Total', 'ASB', 'EVA', 'HYP', 'INF', 'INT', 'LYS', 'PAC', 'REG', 'REP', 'TRNA', 'unclass', 'CDS', 'Unclassified'),
  size = c(
    sum(c(632914, 3703*5, 1818000, 666084, 67101, 59620, 315838, 21870, 433958, 2786*5, 3589827)),
    632914, 3703*5, 1818000, 666084, 67101, 59620, 315838, 21870, 433958, 2786*5, 3589827, 2164127, 1425700
  )
)

# 缩小节点大小以确保节点之间的距离足够大
vertices$size <- vertices$size * 0.5 # 将节点的尺寸进一步缩小

# 创建边数据，建立父子关系
edges <- data.frame(
  from = c(rep('Total', 11), 'unclass', 'unclass'),
  to = c('ASB', 'EVA', 'HYP', 'INF', 'INT', 'LYS', 'PAC', 'REG', 'REP', 'TRNA', 'unclass', 'CDS', 'Unclassified')
)

# 创建图对象
mygraph <- graph_from_data_frame(edges, vertices = vertices)

# 绘制层次结构的圆形图
ggraph(mygraph, layout = 'circlepack', weight = size) +
  # 绘制节点的圆圈，使用fill为NA使圆圈透明，增加边框
  geom_node_circle(color = "black", size = 0.72, fill = NA, show.legend = FALSE) + # 较细的边框，确保边界清晰且不重叠
  
  # 显示文本并动态调整字体大小
  geom_node_text(aes(label = name), 
                 size = 3,  # 统一使用较大字体，以便即使在小节点中也可见
                 fontface = "bold", 
                 color = "black") +  # 使用黑色字体以确保清晰度
  
  theme_void() +
  theme(legend.position = "none") +
  
  # 添加标题，并将标题的字体大小设为 18
  ggtitle("总的被聚类数量的层次结构圆形图") +
  theme(plot.title = element_text(hjust = 0.5, size = 18)) # 可以调整 "size" 的值来改变标题的大小
  library(ggraph)
library(igraph)
library(tidyverse)
library(ggdist)
library(glue)
library(ggtext)
library(patchwork)
# 读取蛋白质数据文件
data <- read_csv("C:/Users/hantao/Documents/output_summary.csv") # 请将路径替换为实际数据文件路径
# 加载所需的包

protein_data <- data %>%
  select(protein_id, length, category) %>%
  filter(!is.na(length))

# 计算统计信息
mean_length <- mean(protein_data$length, na.rm = TRUE)
median_length <- median(protein_data$length, na.rm = TRUE)
n_proteins <- nrow(protein_data)

# 设置图表的颜色和字体
bg_color <- "grey97"
font_family <- "Times New Roman"

# 创建绘图副标题
plot_subtitle <- glue("Length distribution of proteins classified into various categories\n",
                      "from the given dataset. A total of {scales::number(n_proteins, big.mark = ',')} proteins\n",
                      "were analyzed. The median length and mean length are shown.")

# 绘制蛋白质长度分布图
#
p <- protein_data %>%
  ggplot(aes(category, length)) +
  stat_halfeye(fill_type = "segments", alpha = 0.6, adjust = 1.5) +
  stat_interval() +
  stat_summary(geom = "point", fun = median) +
  geom_hline(yintercept = median_length, col = "grey30", lty = "dashed") +
  annotate("text", x = 1.5, y = median_length + 50, label = "Median length",
           family = font_family, size = 3, hjust = 0) +
  scale_y_log10() +
  coord_flip(clip = "off") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(col = "none") +
  labs(
    title = toupper("Protein Length Distribution"),
    subtitle = plot_subtitle,
    caption = "Data source: Your Dataset.<br>Visualization: Generated by OpenAI Assistant",
    x = NULL,
    y = "Length (in amino acids)"
  ) +
  theme_minimal(base_family = font_family) +
  theme(
    plot.background = element_rect(color = NA, fill = bg_color),
    panel.grid = element_blank(),
    panel.grid.major.x = element_line(linewidth = 0.1, color = "grey75"),
    plot.title = element_text(family = font_family, face = "bold"),
    plot.title.position = "plot",
    plot.subtitle = element_textbox_simple(
      margin = margin(t = 4, b = 16), size = 10),
    plot.caption = element_textbox_simple(
      margin = margin(t = 12), size = 7
    ),
    plot.caption.position = "plot",
    axis.text.y = element_text(hjust = 0, margin = margin(r = -10), family = font_family, face = "bold"),
    plot.margin = margin(4, 4, 4, 4)
  )

# 创建图例数据框（在图中）
df_for_legend <- protein_data %>%
  filter(category == "ASB_classified")

p_legend <- df_for_legend %>%
  ggplot(aes(category, length)) +
  stat_halfeye(fill_type = "segments", alpha = 0.3) +
  stat_interval() +
  stat_summary(geom = "point", fun = median) +
  annotate(
    "richtext",
    x = c(0.8, 0.8, 0.8, 1.4, 1.8),
    y = c(100, 500, 300, 240, 400),
    label = c("50 % of lengths<br>fall within this range", "95 % of lengths", 
              "80 % of lengths", "Median", "Distribution<br>of lengths"),
    fill = NA, label.size = 0, family = font_family, size = 2, vjust = 1,
  ) +
  geom_curve(
    data = data.frame(
      x = c(0.7, 0.80, 0.80, 1.225, 1.8),
      xend = c(0.95, 0.95, 0.95, 1.075, 1.8), 
      y = c(180, 500, 300, 230, 380),
      yend = c(180, 500, 300, 210, 250)),
    aes(x = x, xend = xend, y = y, yend = yend),
    stat = "unique", curvature = 0.2, size = 0.2, color = "grey12",
    arrow = arrow(angle = 20, length = unit(1, "mm"))
  ) +
  coord_flip(xlim = c(0.75, 1.3), ylim = c(0, 600), expand = TRUE) +
  guides(color = "none") +
  labs(title = "Legend") +
  theme_void(base_family = font_family) +
  theme(plot.title = element_text(family = font_family, size = 9, face = "bold",
                                  hjust = 0.075),
        plot.background = element_rect(color = "grey30", size = 0.2, fill = bg_color))

# 将自定义图例插入到图中
p + inset_element(p_legend, l = 0.6, r = 1.0, t = 0.99, b = 0.7, clip = FALSE)
